### ISSUE TITLE
collaborator-level access

### ISSUE THREAD

**Issue by nspon** [Endmind/Endminds-blocks#1]
Hi @Endmind ! Could you please add me as a collaborator to this repository? I have reorganized the file structure and would like to make a pull request for you to have a look at :)

**Comment by Endmind** [comment]
ok)

**Comment by Endmind** [comment]
Hi @nspon ! I added you to this repository as a collaborator! Make
something better than I did!

**Comment by nspon** [comment]
Thanks, appreciate it! Let's make it top notch ;)
