### ISSUE TITLE
Updated branches

### ISSUE THREAD

**Issue by nspon** [Endmind/Endminds-blocks#2]
Hi! I have pushed the restructured repo onto `dev` and `master` branches. I suggest we get rid of the `main` branch or reuse it for versioning, and make `master` our state-of-the-art branch, keeping `dev` as our primary development sandbox. Let me know what you think!

**Comment by Endmind** [comment]
bruh its really uncomfortable for users to manually download every file from this list(

**Comment by Endmind** [comment]
also i updated to v1.1.1 and gonna update to v1.2.0
